# Generated by Django 5.2.6 on 2025-09-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '블로그', 'verbose_name_plural': '블로그 목록'},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
