# Generated by Django 5.2.6 on 2025-09-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d/thumbnail', verbose_name='썸네일'),
        ),
    ]
